<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sisa hari_style__ListImageCanvas-sc-1sl_3e9b67</name>
   <tag></tag>
   <elementGuidId>81ea75b1-08e8-4b6b-93d8-fafadf1c5627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='182395-182395']/div/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bantu Mereka Kesulitan Bekerja di Tengah Covid-19</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imgix.kitabisa.com/e8621cf8-d25c-4d2d-af08-d2a5f58aae43.jpg?ar=16:9&amp;w=214&amp;auto=format,compress</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__ListImageCanvas-sc-1sl4ulh-3 cTDNTQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;182395-182395&quot;)/div[@class=&quot;style__ListContainer-sc-1sl4ulh-0 eDEnsS&quot;]/figure[@class=&quot;style__ListFigureCanvas-sc-1sl4ulh-1 Zpwgz&quot;]/img[@class=&quot;style__ListImageCanvas-sc-1sl4ulh-3 cTDNTQ&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='182395-182395']/div/figure/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bantu Mereka Kesulitan Bekerja di Tengah Covid-19']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/figure/img</value>
   </webElementXpaths>
</WebElementEntity>
